### PR TITLE
33 add optional arg `.by` for grouping

### LINKED ISSUE #21: upkeep: squelch warning in `test-aggregate_alignment_loanbook_exposure.R`
When I run tests locally, I get the following warning
``` shell
Warning (test-aggregate_alignment_loanbook_exposure.R:41:1): (code run outside of `test_that()`)
Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(group_vars)

  # Now:
  data %>% select(all_of(group_vars))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
Backtrace:
     ▆
  1. ├─test_data_aggregate_alignment_loanbook_exposure_net %>% ... at test-aggregate_alignment_loanbook_exposure.R:41:1
  2. ├─pacta.multi.loanbook.analysis::aggregate_alignment_loanbook_exposure(...)
  3. │ └─... %>% ... at pacta.multi.loanbook.analysis/R/aggregate_alignment_loanbook_exposure.R:132:3
  4. ├─dplyr::arrange(...)
  5. ├─dplyr::relocate(...)
  6. └─dplyr:::relocate.data.frame(...)
  7.   └─dplyr:::eval_relocate(...)
  8.     └─tidyselect::eval_select(...)
  9.       └─tidyselect:::eval_select_impl(...)
 10.         ├─tidyselect:::with_subscript_errors(...)
 11.         │ └─rlang::try_fetch(...)
 12.         │   └─base::withCallingHandlers(...)
 13.         └─tidyselect:::vars_select_eval(...)
 14.           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 15.             └─tidyselect:::eval_c(expr, data_mask, context_mask)
 16.               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 17.                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 18.                   └─tidyselect:::eval_c(expr, data_mask, context_mask)
 19.                     └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 20.                       └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 21.                         └─tidyselect:::eval_sym(expr, data_mask, context_mask)
```

changing this:
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/blob/a8169803978e8409ac71cfea8f8b84be539c2d31/R/aggregate_alignment_loanbook_exposure.R#L137-L142

to this:
``` r
    dplyr::relocate(
      dplyr::all_of(
        c(
          group_vars, "n_companies", "n_companies_aligned",
          "share_companies_aligned", "exposure_weighted_net_alignment"
        )
      )
    ) %>%
```
squelches the warning

### LINKED ISSUE #33: add filter/group/aggregate functionality
see ecf risk sup, on ADO https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10322

### PR DESCRIPTION
**Pull request by jacobvjk**
closes #33 
closes #21 

- calculation of net alignment metric does not depend on any grouping information (previously depended on `group_id`, which represented loan books)
- for all functions in `calculate_company_alignment_metric.R` this means they now truly return company level information without any references to loan books or other groups previously implied by `group_id`
- `aggregate_alignment_loanbook_exposure()` gains argument `.by` which can be used to define the level of aggregation for loan books
  - Default is `NULL` which means that aggregation happens without grouping. This corresponds to the meta loan book when multiple loan books are processed.
  - `.by` accepts character vectors as inputs. Providing more than one variable to group by is possible
  - the groups must be available in `matched_prioritized`

### CODE REVIEW

**Comment by jacobvjk** [comment]
@jdhoffa I think this PR now covers what we want to achieve here. Given the extent of the changes here, I am keeping it as a draft for now and would ask for your initial review. I expect there are probably a few things that could be changed cosmetically that we may want to add as well

File: R/aggregate_alignment_loanbook_exposure.R [hunk 1]
```diff
@@ -5,46 +5,127 @@
 #' @param level Character. Vector that indicates if the aggregate alignment
 #'   metric should be returned based on the net technology deviations (`net`) or
 #'   disaggregated into buildout and phaseout technologies (`bo_po`).
+#' @param .by <tidy-select> Character. Optionally, a selection of columns to
+#'   group by, instead. All columns indicated must be available variables in the
```
Comment (jdhoffa) [inline R/aggregate_alignment_loanbook_exposure.R:9]: the "instead" there feels a bit strange?

File: R/aggregate_alignment_loanbook_exposure.R [hunk 2]
```diff
@@ -5,46 +5,127 @@
...
+#'   `matched` data set. The intended use case is to allow analyzing the loan
+#'   books by additional traits of interest, such as types of financial
+#'   institutions.
```
Comment (jdhoffa) [inline R/aggregate_alignment_loanbook_exposure.R:12]: NIT: Maybe mention that critical columns can't be used as grouping columns? (e.g. you can't group by `loan_size_outstanding`)

File: R/aggregate_alignment_loanbook_exposure.R [hunk 3]
```diff
@@ -5,46 +5,127 @@
...
+    group_vars = group_vars,
+    .by = .by
   )
 
+  if (!is.null(.by)) {
+    if (!inherits(.by, "character")) {
+      stop(glue::glue("`.by` must be a character vector. Your input is {class(.by)}."))
+    }
+    group_vars <- c(.by, group_vars)
+  }
```
Comment (jdhoffa) [inline R/aggregate_alignment_loanbook_exposure.R:42]: NIT: Does this work if you pass `.by` a `tidyselect` function? (e.g. `.by = starts_with("x")`)? I genuinely don't know haha

File: R/aggregate_alignment_loanbook_exposure.R [hunk 4]
```diff
@@ -85,81 +166,72 @@ aggregate_alignment_loanbook_exposure <- function(data,
...
+  )
 
   return(out)
 }
 
 validate_input_data_aggregate_alignment_loanbook_exposure <- function(data,
                                                                       matched,
-                                                                      group_vars) {
+                                                                      group_vars,
+                                                                      .by = NULL) {
```
Comment (jdhoffa) [inline R/aggregate_alignment_loanbook_exposure.R:214]: Does this function need both `group_vars` and `.by` as arguments? that seems like it would be a bit confusing?

File: tests/testthat/test-aggregate_alignment_loanbook_exposure.R [hunk 5]
```diff
@@ -68,47 +68,178 @@ test_that("number of identified companies equals unique list of companies in inp
...
   expect_equal(
-    c(names(test_output_aggregate_alignment_loanbook_exposure_bopo), exposure_columns),
-    names(test_output_aggregate_alignment_loanbook_exposure_net)
+    c(names(test_output_aggregate_alignment_loanbook_exposure_bopo$aggregate), exposure_columns),
+    names(test_output_aggregate_alignment_loanbook_exposure_net$aggregate)
   )
 })
+
+# When an additional variable is passed via group_var, add group_var to
+# variables considered in aggregation (GH: 33)
```
Comment (jdhoffa) [inline tests/testthat/test-aggregate_alignment_loanbook_exposure.R:110]: I think the tests are out of sync? You mention `group_var`, but I believe this has been superseded by the `.by` argument? (this happens in many places below).

Unless I misunderstand?

**Review by jdhoffa — CHANGES_REQUESTED** [review]
A check-point review and some requested changes

Let me know when this is ready for a more in-depth review and I will test it out in more detail locally

**Comment by jdhoffa** [comment]
NIT: maybe also change the name of the PR, since the argument is now called `.by`?

File: R/aggregate_alignment_loanbook_exposure.R (hunk 2 above)
Comment (jacobvjk) [reply R/aggregate_alignment_loanbook_exposure.R:12]: probably a good idea, but maybe there should be a check that ensures this is not happening then

File: R/calculate_company_alignment_metric.R [hunk 6]
```diff
@@ -324,12 +360,12 @@ fill_missing_direction <- function(data) {
   # there is currently no way to use data masking inside tidyr::nesting()
   # see https://github.com/tidyverse/tidyr/issues/971#issuecomment-985671947
   # the following line is a workaround to avoid the R CMD NOTE
-  group_id <- name_abcd <- sector <- activity_unit <- region <- scenario_source <- scenario <- year <- NULL
+  name_abcd <- sector <- activity_unit <- region <- scenario_source <- scenario <- year <- NULL
```
[the remark this answers is not in the document]
Comment (jacobvjk) [reply R/calculate_company_alignment_metric.R:363]: I know. it's madness

File: tests/testthat/test-aggregate_alignment_loanbook_exposure.R (hunk 5 above)
Comment (jacobvjk) [reply tests/testthat/test-aggregate_alignment_loanbook_exposure.R:110]: No, you very much spotted that correctly

File: R/aggregate_alignment_loanbook_exposure.R (hunk 3 above)
Comment (jacobvjk) [reply R/aggregate_alignment_loanbook_exposure.R:47]: turns out that it does not.. I guess I will need to adapt the documentation

**Review by jdhoffa — APPROVED** [review]
lgtm!! 🚀
